version: "3.9"
services:
 mysqldb:
    container_nae: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddemProject
    volumes:
      - mysql-data:/var/lib/mysql  
    ports:
     - "3306:3306"
  spring-app:
    image: kaddem7:latest 
    container_name:kaddem7
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb
