version: "3.9"
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=kaddemProject
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
  kaddem:
    image: aminamhadhbi/kaddem:83
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - mysql-standalone
