version: '3'
services:
  # Spring Boot Application
  spring-app:
    image: your-spring-app-image:latest  # Replace with the actual image name
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/kaddemProject?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root_password  # Set your desired database password
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - logging.file.path=/var/log/Gestion-Facture-LogFile
      - logging.file.max-size=10MB
      - logging.level.root=info
      - spring.mvc.format.date=yyyy-MM-dd
    depends_on:
      - mysql-db  # Ensure MySQL is started before the Spring Boot app

  # MySQL Database
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Set your desired root password
      MYSQL_DATABASE: kaddemProject
    volumes:
      - mysql-data:/var/lib/mysql  # Persist MySQL data

  # Your third service (kaddem)
  kaddem:
    image: aminamhadhbi/kaddem:14
    container_name: kaddem-container  # Set a custom container name
    ports:
      - 8055:8055
    restart: unless-stopped
    depends_on:
      - mysql-db

volumes:
  mysql-data:  # Define the "mysql-data" volume
