version: "3.9"

services:
  container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
     MYSQL_ROOT_PASSWORD= root
    volumes:
     - /home/mysql/data:/var/liv/mysql
       
  kaddem:
    image: kaddem 
    container_name: kaddem
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
